### ISSUE TITLE
FGVC-Aircraft labels and tree leaf node IDs not matching

### ISSUE THREAD

**Issue by Depanshu-Sani** [ltong1130ztr/HAFrame#2]
I used the preprocessing script and the tree given in the repository. However, I observed that there are 2/100 classes in the images directory that were not matched to two of the leaf node IDs. 
The unmatched image labels are:
`v-F` and `v-F-16-A`

The unmatched tree leaf node IDs are:
`v-F-slash-A-18` and `v-F-16A-slash-B`

By looking at their naming conventions, I am assuming that (`v-F`, `v-F-slash-A-18`) and (`v-F-16-A`, `v-F-16A-slash-B`) pairs should be matched. Could you please clarify if this is indeed the case?

_Edit: I plan to rename the directory names so that I don't have to edit the code to handle the mapping of these labels. It would be great if you could at least confirm if this mapping is correct before actually fixing the error in preprocessing step._

**Comment by ltong1130ztr** [comment]
Thank you for your feedback. You are correct, there's a bug in my dataset preprocessing script causing the name inconsistency: /HAFrame/_fgvc_aircraft/fgvc_dataset_preprocessing.py

```
def annotation_split(line):
    if line[-1] == '\n':
        line = line[:-1] # get rid of '\n'
    tokens = line.split(' ')
    img_name = tokens[0]
    label = ' '.join(tokens[1:])
    return img_name, label
```
should have been:
```
def annotation_split(line):
    if line[-1] == '\n':
        line = line[:-1] # get rid of '\n'
    tokens = line.split(' ')
    img_name = tokens[0]
    label = ' '.join(tokens[1:])
    label = label.replace("/","-slash-")
    return img_name, label
```
This is due to the original variants level labels **F-16A/B** and **F/A-18** having forward-slash in their label names, affecting the associated ImageFolder path, so I replaced "/" with "-slash-": **F-16A-slash-B** and **F-slash-A-18**. The added prefix "v-" indicates both labels are variants level labels. I've fixed it.
